### ISSUE TITLE
Request to update the instructions

### ISSUE THREAD

**Issue by ghost** [Gjum/voxelmap-cache#4]
I've been at this for hours, not a single thing wants to work. I rendered in all the 'tiles' with VoxelMap and placed them in /tiles/terrain/z0/, I run the python script with python and the pillow addon installed and absolutely nothing. Python output jack shit. Oh wait there's more, I was supposed to compile cargo? You mean the program that has had SSL problems since 2014? Oh yeah, they're still around. Was this ever a successful project?

**Comment by Gjum** [comment]
I'm not sure what problem you are describing. Some of the Python scripts might output diagnostics to `stderr`, if that helps.

**Comment by ghost** [comment]
Sorry for my rudeness, usually this many things breaking at once doesn't happen. I hopped on a linux VM to sort things out because Windows is crap, got past the stupid SSLs errors in cargo however it appears to be missing a file `result.rs` from `/src/libcore`. 

Error:
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5```

**Comment by ghost** [comment]
I figured out how the stitcher works, there were a lot more pre-requisites than listed. Somethings still seem to be on the finicky side, though I'll do more testing before I bug ya any further. Sorry if I offended you with my original post.
